name: Build frontend assets

on:
  workflow_call:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: node

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          yarn

      - name: Build
        run: |
          yarn build

      - name: Publish node packages
        run: |
          yarn publish --version ${{ github.event.release.tag_name }}

