name: Build frontend assets

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: node

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          yarn

      - name: Build
        run: |
          yarn build

      - name: Upload frontend assets
        uses: actions/upload-artifact@v4
        with:
          name: frontend-assets
          path: src/jsx/server/static
