name: Test Python Package

on:
  pull_request:
    branches:
      - main
      - dev/v\d+\.\d+\.\d+
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  build:
    uses: xpodev/py-jsx/.github/workflows/build-frontend-assets.yml@main

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install fastapi uvicorn httpx

      - name: Downloading the latest version of the frontend assets
        uses: actions/download-artifact@v4
        with:
          name: frontend-assets
          path: src/jsx/server/static

      - name: Run tests
        working-directory: ${{ github.workspace }}
        run: |
          python -m unittest discover -s tests -p 'test_*.py' -t ${{ github.workspace }}
